// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGu6AZp4a86wm5kBI3DnkM-OvcKmCYAL4',
    appId: '1:482571695045:web:be78d6ee6ecfd06f18d1ac',
    messagingSenderId: '482571695045',
    projectId: 'miaged-4a5bc',
    authDomain: 'miaged-4a5bc.firebaseapp.com',
    storageBucket: 'miaged-4a5bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq3l_HdYo32M2X3ko4CTVUZD79ITcceRs',
    appId: '1:482571695045:android:27bb63139a4314b518d1ac',
    messagingSenderId: '482571695045',
    projectId: 'miaged-4a5bc',
    storageBucket: 'miaged-4a5bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMcct7KVIm7yTRe-GlmFedgT1GHHIEBWE',
    appId: '1:482571695045:ios:a150ae4ed0cdd95218d1ac',
    messagingSenderId: '482571695045',
    projectId: 'miaged-4a5bc',
    storageBucket: 'miaged-4a5bc.appspot.com',
    iosBundleId: 'com.example.miaged',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMcct7KVIm7yTRe-GlmFedgT1GHHIEBWE',
    appId: '1:482571695045:ios:2fba5629ccbe0a0018d1ac',
    messagingSenderId: '482571695045',
    projectId: 'miaged-4a5bc',
    storageBucket: 'miaged-4a5bc.appspot.com',
    iosBundleId: 'com.example.miaged.RunnerTests',
  );
}
